
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;

	private global::Gtk.Action FileAction;

	private global::Gtk.Action FileAction1;

	private global::Gtk.Action PlayerAction;

	private global::Gtk.Action NewPlayerAction;

	private global::Gtk.Action EditPlayerAction;

	private global::Gtk.Action SeasonAction;

	private global::Gtk.Action StartAction;

	private global::Gtk.Action EditAction;

	private global::Gtk.Action TrainingAction;

	private global::Gtk.Action StartAction1;

	private global::Gtk.Action NewTypeAction;

	private global::Gtk.Action NotificationsAction;

	private global::Gtk.Action ViewAction;

	private global::Gtk.Action ExitAction;

	private global::Gtk.Action RecordsOfPresenceAction;

	private global::Gtk.Action ViewRecordsAction;

	private global::Gtk.VBox vbox1;

	private global::Gtk.MenuBar menubar1;

	private global::Gtk.Notebook notebook1;

	private global::Gtk.Label label1;

	private global::Gtk.VBox vbox2;

	private global::Gtk.HBox hbox1;

	private global::Gtk.Label label10;

	private global::Gtk.Entry entry1;

	private global::Gtk.HBox hbox2;

	private global::Gtk.Label label11;

	private global::Gtk.Entry entry2;

	private global::Gtk.HBox hbox3;

	private global::Gtk.Label label12;

	private global::Gtk.Entry entry3;

	private global::Gtk.HBox hbox4;

	private global::Gtk.Label label13;

	private global::Gtk.Entry entry4;

	private global::Gtk.VBox vbox3;

	private global::Gtk.HBox hbox5;

	private global::Gtk.Label label14;

	private global::Gtk.Entry entry5;

	private global::Gtk.HBox hbox7;

	private global::Gtk.Button button2;

	private global::Gtk.Label label2;

	private global::Gtk.VBox vbox4;

	private global::Gtk.ScrolledWindow GtkScrolledWindow;

	private global::Gtk.NodeView nodeview1;

	private global::Gtk.HBox hbox8;

	private global::Gtk.Button button1;

	private global::Gtk.Button button5;

	private global::Gtk.Label label3;

	private global::Gtk.VBox vbox8;

	private global::Gtk.HBox hbox14;

	private global::Gtk.VBox vbox10;

	private global::Gtk.HBox hbox15;

	private global::Gtk.Label label19;

	private global::Gtk.Entry entry7;

	private global::Gtk.HBox hbox16;

	private global::Gtk.Label label20;

	private global::Gtk.Entry entry9;

	private global::Gtk.HBox hbox17;

	private global::Gtk.Label label21;

	private global::Gtk.Entry entry10;

	private global::Gtk.VBox vbox11;

	private global::Gtk.Label label22;

	private global::Gtk.ScrolledWindow GtkScrolledWindow4;

	private global::Gtk.NodeView nodeview2;

	private global::Gtk.VBox vbox9;

	private global::Gtk.VBox vbox28;

	private global::Gtk.HBox hbox24;

	private global::Gtk.Label label40;

	private global::Gtk.Entry entry6;

	private global::Gtk.HBox hbox25;

	private global::Gtk.Label label43;

	private global::Gtk.Entry entry11;

	private global::Gtk.HBox hbox26;

	private global::Gtk.HBox hbox18;

	private global::Gtk.Button button6;

	private global::Gtk.Label label4;

	private global::Gtk.VBox vbox12;

	private global::Gtk.VBox vbox13;

	private global::Gtk.HBox hbox30;

	private global::Gtk.VBox vbox31;

	private global::Gtk.HBox hbox32;

	private global::Gtk.Label label42;

	private global::Gtk.Entry entry17;

	private global::Gtk.ScrolledWindow GtkScrolledWindow1;

	private global::Gtk.NodeView nodeview4;

	private global::Gtk.VBox vbox14;

	private global::Gtk.VBox vbox29;

	private global::Gtk.HBox hbox27;

	private global::Gtk.Label label38;

	private global::Gtk.Entry entry13;

	private global::Gtk.HBox hbox28;

	private global::Gtk.Label label39;

	private global::Gtk.Entry entry14;

	private global::Gtk.HBox hbox29;

	private global::Gtk.HBox hbox19;

	private global::Gtk.Button button7;

	private global::Gtk.Label label5;

	private global::Gtk.VBox vbox6;

	private global::Gtk.HBox hbox10;

	private global::Gtk.VBox vbox7;

	private global::Gtk.HBox hbox11;

	private global::Gtk.VBox vbox26;

	private global::Gtk.VBox vbox30;

	private global::Gtk.Label label15;

	private global::Gtk.HBox hbox31;

	private global::Gtk.Label label41;

	private global::Gtk.Entry entry16;

	private global::Gtk.HBox hbox6;

	private global::Gtk.Label label16;

	private global::Gtk.ComboBoxEntry comboboxentry1;

	private global::Gtk.HBox hbox12;

	private global::Gtk.Label label17;

	private global::Gtk.Entry entry8;

	private global::Gtk.HBox hbox13;

	private global::Gtk.Button button4;

	private global::Gtk.VBox vbox16;

	private global::Gtk.Label label26;

	private global::Gtk.ScrolledWindow GtkScrolledWindow3;

	private global::Gtk.NodeView nodeview6;

	private global::Gtk.VBox vbox15;

	private global::Gtk.Label label25;

	private global::Gtk.ScrolledWindow GtkScrolledWindow6;

	private global::Gtk.NodeView nodeview7;

	private global::Gtk.Label label6;

	private global::Gtk.VBox vbox5;

	private global::Gtk.ScrolledWindow GtkScrolledWindow7;

	private global::Gtk.NodeView nodeview8;

	private global::Gtk.HBox hbox9;

	private global::Gtk.VBox vbox27;

	private global::Gtk.HBox hbox23;

	private global::Gtk.Button button3;

	private global::Gtk.Label label8;

	private global::Gtk.VBox vbox17;

	private global::Gtk.ScrolledWindow GtkScrolledWindow2;

	private global::Gtk.NodeView nodeview3;

	private global::Gtk.VBox vbox18;

	private global::Gtk.HBox hbox20;

	private global::Gtk.Label label7;

	private global::Gtk.Label label9;

	private global::Gtk.HBox hbox21;

	private global::Gtk.Label label18;

	private global::Gtk.Label label23;

	private global::Gtk.HBox hbox22;

	private global::Gtk.Label label24;

	private global::Gtk.Label label27;

	private global::Gtk.Label label28;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
		this.FileAction = new global::Gtk.Action("FileAction", global::Mono.Unix.Catalog.GetString("File"), null, null);
		this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString("File");
		w1.Add(this.FileAction, null);
		this.FileAction1 = new global::Gtk.Action("FileAction1", global::Mono.Unix.Catalog.GetString("File"), null, null);
		this.FileAction1.ShortLabel = global::Mono.Unix.Catalog.GetString("File");
		w1.Add(this.FileAction1, null);
		this.PlayerAction = new global::Gtk.Action("PlayerAction", global::Mono.Unix.Catalog.GetString("Player"), null, null);
		this.PlayerAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Player");
		w1.Add(this.PlayerAction, null);
		this.NewPlayerAction = new global::Gtk.Action("NewPlayerAction", global::Mono.Unix.Catalog.GetString("New player"), null, null);
		this.NewPlayerAction.ShortLabel = global::Mono.Unix.Catalog.GetString("New player");
		w1.Add(this.NewPlayerAction, null);
		this.EditPlayerAction = new global::Gtk.Action("EditPlayerAction", global::Mono.Unix.Catalog.GetString("Edit player"), null, null);
		this.EditPlayerAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Edit player");
		w1.Add(this.EditPlayerAction, null);
		this.SeasonAction = new global::Gtk.Action("SeasonAction", global::Mono.Unix.Catalog.GetString("Season"), null, null);
		this.SeasonAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Season");
		w1.Add(this.SeasonAction, null);
		this.StartAction = new global::Gtk.Action("StartAction", global::Mono.Unix.Catalog.GetString("Start"), null, null);
		this.StartAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Start");
		w1.Add(this.StartAction, null);
		this.EditAction = new global::Gtk.Action("EditAction", global::Mono.Unix.Catalog.GetString("Edit"), null, null);
		this.EditAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Edit");
		w1.Add(this.EditAction, null);
		this.TrainingAction = new global::Gtk.Action("TrainingAction", global::Mono.Unix.Catalog.GetString("Training"), null, null);
		this.TrainingAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Training");
		w1.Add(this.TrainingAction, null);
		this.StartAction1 = new global::Gtk.Action("StartAction1", global::Mono.Unix.Catalog.GetString("Start"), null, null);
		this.StartAction1.ShortLabel = global::Mono.Unix.Catalog.GetString("Start");
		w1.Add(this.StartAction1, null);
		this.NewTypeAction = new global::Gtk.Action("NewTypeAction", global::Mono.Unix.Catalog.GetString("New type"), null, null);
		this.NewTypeAction.ShortLabel = global::Mono.Unix.Catalog.GetString("New type");
		w1.Add(this.NewTypeAction, null);
		this.NotificationsAction = new global::Gtk.Action("NotificationsAction", global::Mono.Unix.Catalog.GetString("Notifications"), null, null);
		this.NotificationsAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Notifications");
		w1.Add(this.NotificationsAction, null);
		this.ViewAction = new global::Gtk.Action("ViewAction", global::Mono.Unix.Catalog.GetString("View"), null, null);
		this.ViewAction.ShortLabel = global::Mono.Unix.Catalog.GetString("View");
		w1.Add(this.ViewAction, null);
		this.ExitAction = new global::Gtk.Action("ExitAction", global::Mono.Unix.Catalog.GetString("Exit"), null, null);
		this.ExitAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Exit");
		w1.Add(this.ExitAction, null);
		this.RecordsOfPresenceAction = new global::Gtk.Action("RecordsOfPresenceAction", global::Mono.Unix.Catalog.GetString("Records of presence"), null, null);
		this.RecordsOfPresenceAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Records of presence");
		w1.Add(this.RecordsOfPresenceAction, null);
		this.ViewRecordsAction = new global::Gtk.Action("ViewRecordsAction", global::Mono.Unix.Catalog.GetString("View records"), null, null);
		this.ViewRecordsAction.ShortLabel = global::Mono.Unix.Catalog.GetString("View records");
		w1.Add(this.ViewRecordsAction, null);
		this.UIManager.InsertActionGroup(w1, 0);
		this.AddAccelGroup(this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("Application");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString(@"<ui><menubar name='menubar1'><menu name='FileAction1' action='FileAction1'><menuitem name='ExitAction' action='ExitAction'/></menu><menu name='PlayerAction' action='PlayerAction'><menuitem name='NewPlayerAction' action='NewPlayerAction'/><menuitem name='EditPlayerAction' action='EditPlayerAction'/></menu><menu name='SeasonAction' action='SeasonAction'><menuitem name='StartAction' action='StartAction'/><menuitem name='EditAction' action='EditAction'/></menu><menu name='TrainingAction' action='TrainingAction'><menuitem name='StartAction1' action='StartAction1'/></menu><menu name='NotificationsAction' action='NotificationsAction'><menuitem name='ViewAction' action='ViewAction'/></menu><menu name='RecordsOfPresenceAction' action='RecordsOfPresenceAction'><menuitem name='ViewRecordsAction' action='ViewRecordsAction'/></menu></menubar></ui>");
		this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget("/menubar1")));
		this.menubar1.Name = "menubar1";
		this.vbox1.Add(this.menubar1);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.menubar1]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.notebook1 = new global::Gtk.Notebook();
		this.notebook1.CanFocus = true;
		this.notebook1.Name = "notebook1";
		this.notebook1.CurrentPage = 4;
		this.notebook1.ShowTabs = false;
		// Notebook tab
		global::Gtk.Label w3 = new global::Gtk.Label();
		w3.Visible = true;
		this.notebook1.Add(w3);
		this.label1 = new global::Gtk.Label();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("page1");
		this.notebook1.SetTabLabel(w3, this.label1);
		this.label1.ShowAll();
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.vbox2 = new global::Gtk.VBox();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.label10 = new global::Gtk.Label();
		this.label10.WidthRequest = 120;
		this.label10.Name = "label10";
		this.label10.Ypad = 30;
		this.label10.LabelProp = global::Mono.Unix.Catalog.GetString("Name:");
		this.hbox1.Add(this.label10);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.label10]));
		w4.Position = 0;
		w4.Expand = false;
		w4.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.entry1 = new global::Gtk.Entry();
		this.entry1.WidthRequest = 200;
		this.entry1.CanFocus = true;
		this.entry1.Name = "entry1";
		this.entry1.IsEditable = true;
		this.entry1.InvisibleChar = '●';
		this.hbox1.Add(this.entry1);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.entry1]));
		w5.Position = 1;
		w5.Expand = false;
		w5.Fill = false;
		w5.Padding = ((uint)(20));
		// Container child hbox1.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.label11 = new global::Gtk.Label();
		this.label11.WidthRequest = 125;
		this.label11.Name = "label11";
		this.label11.Xpad = 41;
		this.label11.LabelProp = global::Mono.Unix.Catalog.GetString("Date of birth:");
		this.hbox2.Add(this.label11);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.label11]));
		w6.Position = 0;
		w6.Expand = false;
		w6.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.entry2 = new global::Gtk.Entry();
		this.entry2.WidthRequest = 200;
		this.entry2.CanFocus = true;
		this.entry2.Name = "entry2";
		this.entry2.Text = global::Mono.Unix.Catalog.GetString("dd/mm/yy");
		this.entry2.IsEditable = true;
		this.entry2.InvisibleChar = '●';
		this.hbox2.Add(this.entry2);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.entry2]));
		w7.Position = 1;
		w7.Expand = false;
		w7.Fill = false;
		this.hbox1.Add(this.hbox2);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.hbox2]));
		w8.Position = 2;
		this.vbox2.Add(this.hbox1);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox1]));
		w9.Position = 0;
		w9.Expand = false;
		w9.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.label12 = new global::Gtk.Label();
		this.label12.WidthRequest = 120;
		this.label12.Name = "label12";
		this.label12.Xpad = 40;
		this.label12.Ypad = 30;
		this.label12.LabelProp = global::Mono.Unix.Catalog.GetString("Lastname:");
		this.hbox3.Add(this.label12);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.label12]));
		w10.Position = 0;
		w10.Expand = false;
		w10.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.entry3 = new global::Gtk.Entry();
		this.entry3.WidthRequest = 200;
		this.entry3.CanFocus = true;
		this.entry3.Name = "entry3";
		this.entry3.IsEditable = true;
		this.entry3.InvisibleChar = '●';
		this.hbox3.Add(this.entry3);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.entry3]));
		w11.Position = 1;
		w11.Expand = false;
		w11.Fill = false;
		w11.Padding = ((uint)(20));
		// Container child hbox3.Gtk.Box+BoxChild
		this.hbox4 = new global::Gtk.HBox();
		this.hbox4.Name = "hbox4";
		this.hbox4.Spacing = 6;
		// Container child hbox4.Gtk.Box+BoxChild
		this.label13 = new global::Gtk.Label();
		this.label13.WidthRequest = 125;
		this.label13.Name = "label13";
		this.label13.LabelProp = global::Mono.Unix.Catalog.GetString("Adress:");
		this.hbox4.Add(this.label13);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.label13]));
		w12.Position = 0;
		w12.Expand = false;
		w12.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.entry4 = new global::Gtk.Entry();
		this.entry4.WidthRequest = 200;
		this.entry4.CanFocus = true;
		this.entry4.Name = "entry4";
		this.entry4.IsEditable = true;
		this.entry4.InvisibleChar = '●';
		this.hbox4.Add(this.entry4);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.entry4]));
		w13.Position = 1;
		w13.Expand = false;
		w13.Fill = false;
		this.hbox3.Add(this.hbox4);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.hbox4]));
		w14.Position = 2;
		this.vbox2.Add(this.hbox3);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox3]));
		w15.Position = 1;
		w15.Expand = false;
		w15.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.vbox3 = new global::Gtk.VBox();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox5 = new global::Gtk.HBox();
		this.hbox5.Name = "hbox5";
		this.hbox5.Spacing = 6;
		// Container child hbox5.Gtk.Box+BoxChild
		this.label14 = new global::Gtk.Label();
		this.label14.WidthRequest = 120;
		this.label14.Name = "label14";
		this.label14.Xpad = 40;
		this.label14.Ypad = 30;
		this.label14.LabelProp = global::Mono.Unix.Catalog.GetString("Mobilephone:");
		this.hbox5.Add(this.label14);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.label14]));
		w16.Position = 0;
		w16.Expand = false;
		w16.Fill = false;
		// Container child hbox5.Gtk.Box+BoxChild
		this.entry5 = new global::Gtk.Entry();
		this.entry5.WidthRequest = 200;
		this.entry5.CanFocus = true;
		this.entry5.Name = "entry5";
		this.entry5.IsEditable = true;
		this.entry5.InvisibleChar = '●';
		this.hbox5.Add(this.entry5);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.entry5]));
		w17.Position = 1;
		w17.Expand = false;
		w17.Fill = false;
		w17.Padding = ((uint)(20));
		this.vbox3.Add(this.hbox5);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox5]));
		w18.Position = 0;
		w18.Expand = false;
		w18.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox7 = new global::Gtk.HBox();
		this.hbox7.Name = "hbox7";
		this.hbox7.Spacing = 6;
		// Container child hbox7.Gtk.Box+BoxChild
		this.button2 = new global::Gtk.Button();
		this.button2.WidthRequest = 65;
		this.button2.CanFocus = true;
		this.button2.Name = "button2";
		this.button2.UseUnderline = true;
		this.button2.Label = global::Mono.Unix.Catalog.GetString("Save");
		this.hbox7.Add(this.button2);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.button2]));
		w19.Position = 0;
		w19.Fill = false;
		this.vbox3.Add(this.hbox7);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox7]));
		w20.Position = 1;
		w20.Expand = false;
		w20.Fill = false;
		w20.Padding = ((uint)(20));
		this.vbox2.Add(this.vbox3);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.vbox3]));
		w21.Position = 2;
		w21.Expand = false;
		w21.Fill = false;
		this.notebook1.Add(this.vbox2);
		global::Gtk.Notebook.NotebookChild w22 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1[this.vbox2]));
		w22.Position = 1;
		// Notebook tab
		this.label2 = new global::Gtk.Label();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("page2");
		this.notebook1.SetTabLabel(this.vbox2, this.label2);
		this.label2.ShowAll();
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.vbox4 = new global::Gtk.VBox();
		this.vbox4.Name = "vbox4";
		this.vbox4.Spacing = 6;
		// Container child vbox4.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.nodeview1 = new global::Gtk.NodeView();
		this.nodeview1.CanFocus = true;
		this.nodeview1.Name = "nodeview1";
		this.GtkScrolledWindow.Add(this.nodeview1);
		this.vbox4.Add(this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.GtkScrolledWindow]));
		w24.Position = 0;
		// Container child vbox4.Gtk.Box+BoxChild
		this.hbox8 = new global::Gtk.HBox();
		this.hbox8.Name = "hbox8";
		this.hbox8.Spacing = 6;
		// Container child hbox8.Gtk.Box+BoxChild
		this.button1 = new global::Gtk.Button();
		this.button1.CanFocus = true;
		this.button1.Name = "button1";
		this.button1.UseUnderline = true;
		this.button1.Label = global::Mono.Unix.Catalog.GetString("Delete");
		this.hbox8.Add(this.button1);
		global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.button1]));
		w25.Position = 0;
		w25.Expand = false;
		w25.Fill = false;
		// Container child hbox8.Gtk.Box+BoxChild
		this.button5 = new global::Gtk.Button();
		this.button5.CanFocus = true;
		this.button5.Name = "button5";
		this.button5.UseUnderline = true;
		this.button5.Label = global::Mono.Unix.Catalog.GetString("Update");
		this.hbox8.Add(this.button5);
		global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.button5]));
		w26.Position = 1;
		w26.Expand = false;
		w26.Fill = false;
		this.vbox4.Add(this.hbox8);
		global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.hbox8]));
		w27.Position = 1;
		w27.Expand = false;
		w27.Fill = false;
		this.notebook1.Add(this.vbox4);
		global::Gtk.Notebook.NotebookChild w28 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1[this.vbox4]));
		w28.Position = 2;
		// Notebook tab
		this.label3 = new global::Gtk.Label();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("page3");
		this.notebook1.SetTabLabel(this.vbox4, this.label3);
		this.label3.ShowAll();
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.vbox8 = new global::Gtk.VBox();
		this.vbox8.Name = "vbox8";
		this.vbox8.Spacing = 6;
		// Container child vbox8.Gtk.Box+BoxChild
		this.hbox14 = new global::Gtk.HBox();
		this.hbox14.Name = "hbox14";
		this.hbox14.Spacing = 6;
		// Container child hbox14.Gtk.Box+BoxChild
		this.vbox10 = new global::Gtk.VBox();
		this.vbox10.Name = "vbox10";
		this.vbox10.Spacing = 6;
		// Container child vbox10.Gtk.Box+BoxChild
		this.hbox15 = new global::Gtk.HBox();
		this.hbox15.Name = "hbox15";
		this.hbox15.Spacing = 6;
		// Container child hbox15.Gtk.Box+BoxChild
		this.label19 = new global::Gtk.Label();
		this.label19.WidthRequest = 100;
		this.label19.Name = "label19";
		this.label19.Xpad = 35;
		this.label19.Ypad = 20;
		this.label19.LabelProp = global::Mono.Unix.Catalog.GetString("Name:");
		this.hbox15.Add(this.label19);
		global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.hbox15[this.label19]));
		w29.Position = 0;
		w29.Expand = false;
		w29.Fill = false;
		// Container child hbox15.Gtk.Box+BoxChild
		this.entry7 = new global::Gtk.Entry();
		this.entry7.WidthRequest = 200;
		this.entry7.CanFocus = true;
		this.entry7.Name = "entry7";
		this.entry7.IsEditable = true;
		this.entry7.InvisibleChar = '●';
		this.hbox15.Add(this.entry7);
		global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.hbox15[this.entry7]));
		w30.Position = 1;
		w30.Expand = false;
		w30.Fill = false;
		this.vbox10.Add(this.hbox15);
		global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.vbox10[this.hbox15]));
		w31.Position = 0;
		w31.Expand = false;
		w31.Fill = false;
		// Container child vbox10.Gtk.Box+BoxChild
		this.hbox16 = new global::Gtk.HBox();
		this.hbox16.Name = "hbox16";
		this.hbox16.Spacing = 6;
		// Container child hbox16.Gtk.Box+BoxChild
		this.label20 = new global::Gtk.Label();
		this.label20.WidthRequest = 100;
		this.label20.Name = "label20";
		this.label20.Ypad = 20;
		this.label20.LabelProp = global::Mono.Unix.Catalog.GetString("Start");
		this.hbox16.Add(this.label20);
		global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.hbox16[this.label20]));
		w32.Position = 0;
		w32.Expand = false;
		w32.Fill = false;
		// Container child hbox16.Gtk.Box+BoxChild
		this.entry9 = new global::Gtk.Entry();
		this.entry9.WidthRequest = 200;
		this.entry9.CanFocus = true;
		this.entry9.Name = "entry9";
		this.entry9.Text = global::Mono.Unix.Catalog.GetString("dd/mm/yy");
		this.entry9.IsEditable = true;
		this.entry9.InvisibleChar = '●';
		this.hbox16.Add(this.entry9);
		global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.hbox16[this.entry9]));
		w33.Position = 1;
		w33.Expand = false;
		w33.Fill = false;
		this.vbox10.Add(this.hbox16);
		global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.vbox10[this.hbox16]));
		w34.Position = 1;
		w34.Expand = false;
		w34.Fill = false;
		// Container child vbox10.Gtk.Box+BoxChild
		this.hbox17 = new global::Gtk.HBox();
		this.hbox17.Name = "hbox17";
		this.hbox17.Spacing = 6;
		// Container child hbox17.Gtk.Box+BoxChild
		this.label21 = new global::Gtk.Label();
		this.label21.WidthRequest = 100;
		this.label21.Name = "label21";
		this.label21.Xpad = 35;
		this.label21.Ypad = 20;
		this.label21.LabelProp = global::Mono.Unix.Catalog.GetString("Finish");
		this.hbox17.Add(this.label21);
		global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.hbox17[this.label21]));
		w35.Position = 0;
		w35.Expand = false;
		w35.Fill = false;
		// Container child hbox17.Gtk.Box+BoxChild
		this.entry10 = new global::Gtk.Entry();
		this.entry10.WidthRequest = 200;
		this.entry10.CanFocus = true;
		this.entry10.Name = "entry10";
		this.entry10.Text = global::Mono.Unix.Catalog.GetString("dd/mm/yy");
		this.entry10.IsEditable = true;
		this.entry10.InvisibleChar = '●';
		this.hbox17.Add(this.entry10);
		global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.hbox17[this.entry10]));
		w36.Position = 1;
		w36.Expand = false;
		w36.Fill = false;
		this.vbox10.Add(this.hbox17);
		global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.vbox10[this.hbox17]));
		w37.Position = 2;
		w37.Expand = false;
		w37.Fill = false;
		this.hbox14.Add(this.vbox10);
		global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.hbox14[this.vbox10]));
		w38.Position = 0;
		// Container child hbox14.Gtk.Box+BoxChild
		this.vbox11 = new global::Gtk.VBox();
		this.vbox11.Name = "vbox11";
		this.vbox11.Spacing = 6;
		// Container child vbox11.Gtk.Box+BoxChild
		this.label22 = new global::Gtk.Label();
		this.label22.WidthRequest = 440;
		this.label22.Name = "label22";
		this.label22.LabelProp = global::Mono.Unix.Catalog.GetString("Avaiable players");
		this.vbox11.Add(this.label22);
		global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.vbox11[this.label22]));
		w39.Position = 0;
		w39.Expand = false;
		w39.Fill = false;
		// Container child vbox11.Gtk.Box+BoxChild
		this.GtkScrolledWindow4 = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow4.Name = "GtkScrolledWindow4";
		this.GtkScrolledWindow4.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow4.Gtk.Container+ContainerChild
		this.nodeview2 = new global::Gtk.NodeView();
		this.nodeview2.CanFocus = true;
		this.nodeview2.Name = "nodeview2";
		this.GtkScrolledWindow4.Add(this.nodeview2);
		this.vbox11.Add(this.GtkScrolledWindow4);
		global::Gtk.Box.BoxChild w41 = ((global::Gtk.Box.BoxChild)(this.vbox11[this.GtkScrolledWindow4]));
		w41.Position = 1;
		this.hbox14.Add(this.vbox11);
		global::Gtk.Box.BoxChild w42 = ((global::Gtk.Box.BoxChild)(this.hbox14[this.vbox11]));
		w42.Position = 1;
		w42.Expand = false;
		w42.Fill = false;
		this.vbox8.Add(this.hbox14);
		global::Gtk.Box.BoxChild w43 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.hbox14]));
		w43.Position = 0;
		w43.Expand = false;
		w43.Fill = false;
		// Container child vbox8.Gtk.Box+BoxChild
		this.vbox9 = new global::Gtk.VBox();
		this.vbox9.Name = "vbox9";
		this.vbox9.Spacing = 6;
		// Container child vbox9.Gtk.Box+BoxChild
		this.vbox28 = new global::Gtk.VBox();
		this.vbox28.Name = "vbox28";
		this.vbox28.Spacing = 6;
		// Container child vbox28.Gtk.Box+BoxChild
		this.hbox24 = new global::Gtk.HBox();
		this.hbox24.Name = "hbox24";
		this.hbox24.Spacing = 6;
		// Container child hbox24.Gtk.Box+BoxChild
		this.label40 = new global::Gtk.Label();
		this.label40.WidthRequest = 350;
		this.label40.Name = "label40";
		this.label40.Xpad = 70;
		this.label40.Ypad = 10;
		this.label40.LabelProp = global::Mono.Unix.Catalog.GetString("        Max number of trainings        ");
		this.hbox24.Add(this.label40);
		global::Gtk.Box.BoxChild w44 = ((global::Gtk.Box.BoxChild)(this.hbox24[this.label40]));
		w44.Position = 0;
		w44.Expand = false;
		w44.Fill = false;
		w44.Padding = ((uint)(50));
		// Container child hbox24.Gtk.Box+BoxChild
		this.entry6 = new global::Gtk.Entry();
		this.entry6.CanFocus = true;
		this.entry6.Name = "entry6";
		this.entry6.IsEditable = true;
		this.entry6.InvisibleChar = '●';
		this.hbox24.Add(this.entry6);
		global::Gtk.Box.BoxChild w45 = ((global::Gtk.Box.BoxChild)(this.hbox24[this.entry6]));
		w45.Position = 1;
		w45.Expand = false;
		w45.Fill = false;
		this.vbox28.Add(this.hbox24);
		global::Gtk.Box.BoxChild w46 = ((global::Gtk.Box.BoxChild)(this.vbox28[this.hbox24]));
		w46.Position = 0;
		w46.Expand = false;
		w46.Fill = false;
		// Container child vbox28.Gtk.Box+BoxChild
		this.hbox25 = new global::Gtk.HBox();
		this.hbox25.Name = "hbox25";
		this.hbox25.Spacing = 6;
		// Container child hbox25.Gtk.Box+BoxChild
		this.label43 = new global::Gtk.Label();
		this.label43.WidthRequest = 370;
		this.label43.Name = "label43";
		this.label43.Xpad = 80;
		this.label43.Ypad = 10;
		this.label43.LabelProp = global::Mono.Unix.Catalog.GetString("Max players per season");
		this.hbox25.Add(this.label43);
		global::Gtk.Box.BoxChild w47 = ((global::Gtk.Box.BoxChild)(this.hbox25[this.label43]));
		w47.Position = 0;
		w47.Expand = false;
		w47.Fill = false;
		w47.Padding = ((uint)(40));
		// Container child hbox25.Gtk.Box+BoxChild
		this.entry11 = new global::Gtk.Entry();
		this.entry11.CanFocus = true;
		this.entry11.Name = "entry11";
		this.entry11.IsEditable = true;
		this.entry11.InvisibleChar = '●';
		this.hbox25.Add(this.entry11);
		global::Gtk.Box.BoxChild w48 = ((global::Gtk.Box.BoxChild)(this.hbox25[this.entry11]));
		w48.Position = 1;
		w48.Expand = false;
		w48.Fill = false;
		this.vbox28.Add(this.hbox25);
		global::Gtk.Box.BoxChild w49 = ((global::Gtk.Box.BoxChild)(this.vbox28[this.hbox25]));
		w49.Position = 1;
		w49.Expand = false;
		w49.Fill = false;
		// Container child vbox28.Gtk.Box+BoxChild
		this.hbox26 = new global::Gtk.HBox();
		this.hbox26.Name = "hbox26";
		this.hbox26.Spacing = 6;
		this.vbox28.Add(this.hbox26);
		global::Gtk.Box.BoxChild w50 = ((global::Gtk.Box.BoxChild)(this.vbox28[this.hbox26]));
		w50.Position = 2;
		this.vbox9.Add(this.vbox28);
		global::Gtk.Box.BoxChild w51 = ((global::Gtk.Box.BoxChild)(this.vbox9[this.vbox28]));
		w51.Position = 0;
		this.vbox8.Add(this.vbox9);
		global::Gtk.Box.BoxChild w52 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.vbox9]));
		w52.Position = 1;
		// Container child vbox8.Gtk.Box+BoxChild
		this.hbox18 = new global::Gtk.HBox();
		this.hbox18.Name = "hbox18";
		this.hbox18.Spacing = 6;
		// Container child hbox18.Gtk.Box+BoxChild
		this.button6 = new global::Gtk.Button();
		this.button6.WidthRequest = 65;
		this.button6.CanFocus = true;
		this.button6.Name = "button6";
		this.button6.UseUnderline = true;
		this.button6.Label = global::Mono.Unix.Catalog.GetString("Save");
		this.hbox18.Add(this.button6);
		global::Gtk.Box.BoxChild w53 = ((global::Gtk.Box.BoxChild)(this.hbox18[this.button6]));
		w53.Position = 1;
		w53.Fill = false;
		this.vbox8.Add(this.hbox18);
		global::Gtk.Box.BoxChild w54 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.hbox18]));
		w54.Position = 2;
		w54.Expand = false;
		w54.Fill = false;
		this.notebook1.Add(this.vbox8);
		global::Gtk.Notebook.NotebookChild w55 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1[this.vbox8]));
		w55.Position = 3;
		// Notebook tab
		this.label4 = new global::Gtk.Label();
		this.label4.Name = "label4";
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("page4");
		this.notebook1.SetTabLabel(this.vbox8, this.label4);
		this.label4.ShowAll();
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.vbox12 = new global::Gtk.VBox();
		this.vbox12.Name = "vbox12";
		this.vbox12.Spacing = 6;
		// Container child vbox12.Gtk.Box+BoxChild
		this.vbox13 = new global::Gtk.VBox();
		this.vbox13.Name = "vbox13";
		this.vbox13.Spacing = 6;
		// Container child vbox13.Gtk.Box+BoxChild
		this.hbox30 = new global::Gtk.HBox();
		this.hbox30.Name = "hbox30";
		this.hbox30.Spacing = 6;
		// Container child hbox30.Gtk.Box+BoxChild
		this.vbox31 = new global::Gtk.VBox();
		this.vbox31.Name = "vbox31";
		this.vbox31.Spacing = 6;
		// Container child vbox31.Gtk.Box+BoxChild
		this.hbox32 = new global::Gtk.HBox();
		this.hbox32.Name = "hbox32";
		this.hbox32.Spacing = 6;
		// Container child hbox32.Gtk.Box+BoxChild
		this.label42 = new global::Gtk.Label();
		this.label42.Name = "label42";
		this.label42.Ypad = 20;
		this.label42.LabelProp = global::Mono.Unix.Catalog.GetString("Name:");
		this.hbox32.Add(this.label42);
		global::Gtk.Box.BoxChild w56 = ((global::Gtk.Box.BoxChild)(this.hbox32[this.label42]));
		w56.Position = 0;
		w56.Expand = false;
		w56.Fill = false;
		// Container child hbox32.Gtk.Box+BoxChild
		this.entry17 = new global::Gtk.Entry();
		this.entry17.WidthRequest = 200;
		this.entry17.CanFocus = true;
		this.entry17.Name = "entry17";
		this.entry17.IsEditable = true;
		this.entry17.InvisibleChar = '●';
		this.hbox32.Add(this.entry17);
		global::Gtk.Box.BoxChild w57 = ((global::Gtk.Box.BoxChild)(this.hbox32[this.entry17]));
		w57.Position = 1;
		w57.Expand = false;
		w57.Fill = false;
		this.vbox31.Add(this.hbox32);
		global::Gtk.Box.BoxChild w58 = ((global::Gtk.Box.BoxChild)(this.vbox31[this.hbox32]));
		w58.Position = 0;
		w58.Expand = false;
		w58.Fill = false;
		this.hbox30.Add(this.vbox31);
		global::Gtk.Box.BoxChild w59 = ((global::Gtk.Box.BoxChild)(this.hbox30[this.vbox31]));
		w59.Position = 0;
		w59.Padding = ((uint)(40));
		// Container child hbox30.Gtk.Box+BoxChild
		this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
		this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
		this.nodeview4 = new global::Gtk.NodeView();
		this.nodeview4.WidthRequest = 300;
		this.nodeview4.HeightRequest = 150;
		this.nodeview4.CanFocus = true;
		this.nodeview4.Name = "nodeview4";
		this.GtkScrolledWindow1.Add(this.nodeview4);
		this.hbox30.Add(this.GtkScrolledWindow1);
		global::Gtk.Box.BoxChild w61 = ((global::Gtk.Box.BoxChild)(this.hbox30[this.GtkScrolledWindow1]));
		w61.Position = 1;
		this.vbox13.Add(this.hbox30);
		global::Gtk.Box.BoxChild w62 = ((global::Gtk.Box.BoxChild)(this.vbox13[this.hbox30]));
		w62.Position = 0;
		w62.Expand = false;
		w62.Fill = false;
		this.vbox12.Add(this.vbox13);
		global::Gtk.Box.BoxChild w63 = ((global::Gtk.Box.BoxChild)(this.vbox12[this.vbox13]));
		w63.Position = 0;
		w63.Expand = false;
		w63.Fill = false;
		// Container child vbox12.Gtk.Box+BoxChild
		this.vbox14 = new global::Gtk.VBox();
		this.vbox14.Name = "vbox14";
		this.vbox14.Spacing = 6;
		// Container child vbox14.Gtk.Box+BoxChild
		this.vbox29 = new global::Gtk.VBox();
		this.vbox29.Name = "vbox29";
		this.vbox29.Spacing = 6;
		// Container child vbox29.Gtk.Box+BoxChild
		this.hbox27 = new global::Gtk.HBox();
		this.hbox27.Name = "hbox27";
		this.hbox27.Spacing = 6;
		// Container child hbox27.Gtk.Box+BoxChild
		this.label38 = new global::Gtk.Label();
		this.label38.WidthRequest = 350;
		this.label38.Name = "label38";
		this.label38.Xpad = 70;
		this.label38.Ypad = 10;
		this.label38.LabelProp = global::Mono.Unix.Catalog.GetString("        Max number of trainings        ");
		this.hbox27.Add(this.label38);
		global::Gtk.Box.BoxChild w64 = ((global::Gtk.Box.BoxChild)(this.hbox27[this.label38]));
		w64.Position = 0;
		w64.Expand = false;
		w64.Fill = false;
		w64.Padding = ((uint)(10));
		// Container child hbox27.Gtk.Box+BoxChild
		this.entry13 = new global::Gtk.Entry();
		this.entry13.CanFocus = true;
		this.entry13.Name = "entry13";
		this.entry13.IsEditable = true;
		this.entry13.InvisibleChar = '●';
		this.hbox27.Add(this.entry13);
		global::Gtk.Box.BoxChild w65 = ((global::Gtk.Box.BoxChild)(this.hbox27[this.entry13]));
		w65.Position = 1;
		w65.Expand = false;
		w65.Fill = false;
		this.vbox29.Add(this.hbox27);
		global::Gtk.Box.BoxChild w66 = ((global::Gtk.Box.BoxChild)(this.vbox29[this.hbox27]));
		w66.Position = 0;
		w66.Expand = false;
		w66.Fill = false;
		// Container child vbox29.Gtk.Box+BoxChild
		this.hbox28 = new global::Gtk.HBox();
		this.hbox28.Name = "hbox28";
		this.hbox28.Spacing = 6;
		// Container child hbox28.Gtk.Box+BoxChild
		this.label39 = new global::Gtk.Label();
		this.label39.WidthRequest = 370;
		this.label39.Name = "label39";
		this.label39.Xpad = 80;
		this.label39.Ypad = 10;
		this.label39.LabelProp = global::Mono.Unix.Catalog.GetString("Max players per season");
		this.hbox28.Add(this.label39);
		global::Gtk.Box.BoxChild w67 = ((global::Gtk.Box.BoxChild)(this.hbox28[this.label39]));
		w67.Position = 0;
		w67.Expand = false;
		w67.Fill = false;
		// Container child hbox28.Gtk.Box+BoxChild
		this.entry14 = new global::Gtk.Entry();
		this.entry14.CanFocus = true;
		this.entry14.Name = "entry14";
		this.entry14.IsEditable = true;
		this.entry14.InvisibleChar = '●';
		this.hbox28.Add(this.entry14);
		global::Gtk.Box.BoxChild w68 = ((global::Gtk.Box.BoxChild)(this.hbox28[this.entry14]));
		w68.Position = 1;
		w68.Expand = false;
		w68.Fill = false;
		this.vbox29.Add(this.hbox28);
		global::Gtk.Box.BoxChild w69 = ((global::Gtk.Box.BoxChild)(this.vbox29[this.hbox28]));
		w69.Position = 1;
		w69.Expand = false;
		w69.Fill = false;
		// Container child vbox29.Gtk.Box+BoxChild
		this.hbox29 = new global::Gtk.HBox();
		this.hbox29.Name = "hbox29";
		this.hbox29.Spacing = 6;
		this.vbox29.Add(this.hbox29);
		global::Gtk.Box.BoxChild w70 = ((global::Gtk.Box.BoxChild)(this.vbox29[this.hbox29]));
		w70.Position = 2;
		this.vbox14.Add(this.vbox29);
		global::Gtk.Box.BoxChild w71 = ((global::Gtk.Box.BoxChild)(this.vbox14[this.vbox29]));
		w71.Position = 0;
		// Container child vbox14.Gtk.Box+BoxChild
		this.hbox19 = new global::Gtk.HBox();
		this.hbox19.Name = "hbox19";
		this.hbox19.Spacing = 6;
		// Container child hbox19.Gtk.Box+BoxChild
		this.button7 = new global::Gtk.Button();
		this.button7.WidthRequest = 65;
		this.button7.CanFocus = true;
		this.button7.Name = "button7";
		this.button7.UseUnderline = true;
		this.button7.Label = global::Mono.Unix.Catalog.GetString("Update");
		this.hbox19.Add(this.button7);
		global::Gtk.Box.BoxChild w72 = ((global::Gtk.Box.BoxChild)(this.hbox19[this.button7]));
		w72.Position = 1;
		w72.Fill = false;
		this.vbox14.Add(this.hbox19);
		global::Gtk.Box.BoxChild w73 = ((global::Gtk.Box.BoxChild)(this.vbox14[this.hbox19]));
		w73.Position = 1;
		w73.Expand = false;
		w73.Fill = false;
		this.vbox12.Add(this.vbox14);
		global::Gtk.Box.BoxChild w74 = ((global::Gtk.Box.BoxChild)(this.vbox12[this.vbox14]));
		w74.Position = 1;
		this.notebook1.Add(this.vbox12);
		global::Gtk.Notebook.NotebookChild w75 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1[this.vbox12]));
		w75.Position = 4;
		// Notebook tab
		this.label5 = new global::Gtk.Label();
		this.label5.Name = "label5";
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString("page5");
		this.notebook1.SetTabLabel(this.vbox12, this.label5);
		this.label5.ShowAll();
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.vbox6 = new global::Gtk.VBox();
		this.vbox6.Name = "vbox6";
		this.vbox6.Spacing = 6;
		// Container child vbox6.Gtk.Box+BoxChild
		this.hbox10 = new global::Gtk.HBox();
		this.hbox10.Name = "hbox10";
		this.hbox10.Spacing = 6;
		// Container child hbox10.Gtk.Box+BoxChild
		this.vbox7 = new global::Gtk.VBox();
		this.vbox7.Name = "vbox7";
		this.vbox7.Spacing = 6;
		// Container child vbox7.Gtk.Box+BoxChild
		this.hbox11 = new global::Gtk.HBox();
		this.hbox11.Name = "hbox11";
		this.hbox11.Spacing = 6;
		// Container child hbox11.Gtk.Box+BoxChild
		this.vbox26 = new global::Gtk.VBox();
		this.vbox26.Name = "vbox26";
		this.vbox26.Spacing = 6;
		// Container child vbox26.Gtk.Box+BoxChild
		this.vbox30 = new global::Gtk.VBox();
		this.vbox30.Name = "vbox30";
		this.vbox30.Spacing = 6;
		// Container child vbox30.Gtk.Box+BoxChild
		this.label15 = new global::Gtk.Label();
		this.label15.Name = "label15";
		this.label15.Ypad = 9;
		this.label15.LabelProp = global::Mono.Unix.Catalog.GetString("Enter required data here:");
		this.vbox30.Add(this.label15);
		global::Gtk.Box.BoxChild w76 = ((global::Gtk.Box.BoxChild)(this.vbox30[this.label15]));
		w76.Position = 0;
		w76.Expand = false;
		w76.Fill = false;
		// Container child vbox30.Gtk.Box+BoxChild
		this.hbox31 = new global::Gtk.HBox();
		this.hbox31.Name = "hbox31";
		this.hbox31.Spacing = 6;
		// Container child hbox31.Gtk.Box+BoxChild
		this.label41 = new global::Gtk.Label();
		this.label41.WidthRequest = 125;
		this.label41.Name = "label41";
		this.label41.LabelProp = global::Mono.Unix.Catalog.GetString("Date:");
		this.hbox31.Add(this.label41);
		global::Gtk.Box.BoxChild w77 = ((global::Gtk.Box.BoxChild)(this.hbox31[this.label41]));
		w77.Position = 0;
		w77.Expand = false;
		w77.Fill = false;
		// Container child hbox31.Gtk.Box+BoxChild
		this.entry16 = new global::Gtk.Entry();
		this.entry16.WidthRequest = 200;
		this.entry16.CanFocus = true;
		this.entry16.Name = "entry16";
		this.entry16.Text = global::Mono.Unix.Catalog.GetString("dd/mm/yy");
		this.entry16.IsEditable = true;
		this.entry16.InvisibleChar = '●';
		this.hbox31.Add(this.entry16);
		global::Gtk.Box.BoxChild w78 = ((global::Gtk.Box.BoxChild)(this.hbox31[this.entry16]));
		w78.PackType = ((global::Gtk.PackType)(1));
		w78.Position = 1;
		w78.Expand = false;
		w78.Fill = false;
		this.vbox30.Add(this.hbox31);
		global::Gtk.Box.BoxChild w79 = ((global::Gtk.Box.BoxChild)(this.vbox30[this.hbox31]));
		w79.Position = 1;
		w79.Expand = false;
		w79.Fill = false;
		this.vbox26.Add(this.vbox30);
		global::Gtk.Box.BoxChild w80 = ((global::Gtk.Box.BoxChild)(this.vbox26[this.vbox30]));
		w80.Position = 0;
		w80.Expand = false;
		w80.Fill = false;
		// Container child vbox26.Gtk.Box+BoxChild
		this.hbox6 = new global::Gtk.HBox();
		this.hbox6.Name = "hbox6";
		this.hbox6.Spacing = 6;
		// Container child hbox6.Gtk.Box+BoxChild
		this.label16 = new global::Gtk.Label();
		this.label16.WidthRequest = 125;
		this.label16.Name = "label16";
		this.label16.Xpad = 35;
		this.label16.LabelProp = global::Mono.Unix.Catalog.GetString("Type of training:");
		this.hbox6.Add(this.label16);
		global::Gtk.Box.BoxChild w81 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.label16]));
		w81.Position = 0;
		w81.Expand = false;
		w81.Fill = false;
		w81.Padding = ((uint)(10));
		// Container child hbox6.Gtk.Box+BoxChild
		this.comboboxentry1 = global::Gtk.ComboBoxEntry.NewText();
		this.comboboxentry1.WidthRequest = 200;
		this.comboboxentry1.Name = "comboboxentry1";
		this.hbox6.Add(this.comboboxentry1);
		global::Gtk.Box.BoxChild w82 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.comboboxentry1]));
		w82.Position = 1;
		w82.Expand = false;
		w82.Fill = false;
		this.vbox26.Add(this.hbox6);
		global::Gtk.Box.BoxChild w83 = ((global::Gtk.Box.BoxChild)(this.vbox26[this.hbox6]));
		w83.Position = 1;
		w83.Expand = false;
		w83.Fill = false;
		this.hbox11.Add(this.vbox26);
		global::Gtk.Box.BoxChild w84 = ((global::Gtk.Box.BoxChild)(this.hbox11[this.vbox26]));
		w84.Position = 0;
		w84.Expand = false;
		w84.Fill = false;
		this.vbox7.Add(this.hbox11);
		global::Gtk.Box.BoxChild w85 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.hbox11]));
		w85.Position = 0;
		w85.Expand = false;
		w85.Fill = false;
		// Container child vbox7.Gtk.Box+BoxChild
		this.hbox12 = new global::Gtk.HBox();
		this.hbox12.Name = "hbox12";
		this.hbox12.Spacing = 6;
		// Container child hbox12.Gtk.Box+BoxChild
		this.label17 = new global::Gtk.Label();
		this.label17.WidthRequest = 125;
		this.label17.Name = "label17";
		this.label17.LabelProp = global::Mono.Unix.Catalog.GetString("Duration:");
		this.hbox12.Add(this.label17);
		global::Gtk.Box.BoxChild w86 = ((global::Gtk.Box.BoxChild)(this.hbox12[this.label17]));
		w86.Position = 0;
		w86.Expand = false;
		w86.Fill = false;
		w86.Padding = ((uint)(10));
		// Container child hbox12.Gtk.Box+BoxChild
		this.entry8 = new global::Gtk.Entry();
		this.entry8.WidthRequest = 200;
		this.entry8.CanFocus = true;
		this.entry8.Name = "entry8";
		this.entry8.IsEditable = true;
		this.entry8.InvisibleChar = '●';
		this.hbox12.Add(this.entry8);
		global::Gtk.Box.BoxChild w87 = ((global::Gtk.Box.BoxChild)(this.hbox12[this.entry8]));
		w87.Position = 1;
		w87.Expand = false;
		w87.Fill = false;
		this.vbox7.Add(this.hbox12);
		global::Gtk.Box.BoxChild w88 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.hbox12]));
		w88.Position = 1;
		w88.Expand = false;
		w88.Fill = false;
		// Container child vbox7.Gtk.Box+BoxChild
		this.hbox13 = new global::Gtk.HBox();
		this.hbox13.Name = "hbox13";
		this.hbox13.Spacing = 6;
		// Container child hbox13.Gtk.Box+BoxChild
		this.button4 = new global::Gtk.Button();
		this.button4.WidthRequest = 65;
		this.button4.CanFocus = true;
		this.button4.Name = "button4";
		this.button4.UseUnderline = true;
		this.button4.Label = global::Mono.Unix.Catalog.GetString("Save");
		this.hbox13.Add(this.button4);
		global::Gtk.Box.BoxChild w89 = ((global::Gtk.Box.BoxChild)(this.hbox13[this.button4]));
		w89.Position = 0;
		w89.Fill = false;
		this.vbox7.Add(this.hbox13);
		global::Gtk.Box.BoxChild w90 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.hbox13]));
		w90.Position = 2;
		w90.Expand = false;
		w90.Fill = false;
		this.hbox10.Add(this.vbox7);
		global::Gtk.Box.BoxChild w91 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.vbox7]));
		w91.Position = 0;
		w91.Expand = false;
		w91.Fill = false;
		// Container child hbox10.Gtk.Box+BoxChild
		this.vbox16 = new global::Gtk.VBox();
		this.vbox16.Name = "vbox16";
		this.vbox16.Spacing = 6;
		// Container child vbox16.Gtk.Box+BoxChild
		this.label26 = new global::Gtk.Label();
		this.label26.WidthRequest = 480;
		this.label26.Name = "label26";
		this.label26.Ypad = 10;
		this.label26.LabelProp = global::Mono.Unix.Catalog.GetString("Select avaiable players");
		this.vbox16.Add(this.label26);
		global::Gtk.Box.BoxChild w92 = ((global::Gtk.Box.BoxChild)(this.vbox16[this.label26]));
		w92.Position = 0;
		w92.Expand = false;
		w92.Fill = false;
		// Container child vbox16.Gtk.Box+BoxChild
		this.GtkScrolledWindow3 = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow3.Name = "GtkScrolledWindow3";
		this.GtkScrolledWindow3.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow3.Gtk.Container+ContainerChild
		this.nodeview6 = new global::Gtk.NodeView();
		this.nodeview6.HeightRequest = 150;
		this.nodeview6.CanFocus = true;
		this.nodeview6.Name = "nodeview6";
		this.GtkScrolledWindow3.Add(this.nodeview6);
		this.vbox16.Add(this.GtkScrolledWindow3);
		global::Gtk.Box.BoxChild w94 = ((global::Gtk.Box.BoxChild)(this.vbox16[this.GtkScrolledWindow3]));
		w94.Position = 1;
		this.hbox10.Add(this.vbox16);
		global::Gtk.Box.BoxChild w95 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.vbox16]));
		w95.Position = 1;
		w95.Expand = false;
		w95.Fill = false;
		this.vbox6.Add(this.hbox10);
		global::Gtk.Box.BoxChild w96 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.hbox10]));
		w96.Position = 0;
		w96.Expand = false;
		w96.Fill = false;
		// Container child vbox6.Gtk.Box+BoxChild
		this.vbox15 = new global::Gtk.VBox();
		this.vbox15.Name = "vbox15";
		this.vbox15.Spacing = 6;
		// Container child vbox15.Gtk.Box+BoxChild
		this.label25 = new global::Gtk.Label();
		this.label25.Name = "label25";
		this.label25.LabelProp = global::Mono.Unix.Catalog.GetString("List of trainings");
		this.vbox15.Add(this.label25);
		global::Gtk.Box.BoxChild w97 = ((global::Gtk.Box.BoxChild)(this.vbox15[this.label25]));
		w97.Position = 0;
		w97.Expand = false;
		w97.Fill = false;
		// Container child vbox15.Gtk.Box+BoxChild
		this.GtkScrolledWindow6 = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow6.Name = "GtkScrolledWindow6";
		this.GtkScrolledWindow6.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow6.Gtk.Container+ContainerChild
		this.nodeview7 = new global::Gtk.NodeView();
		this.nodeview7.CanFocus = true;
		this.nodeview7.Name = "nodeview7";
		this.GtkScrolledWindow6.Add(this.nodeview7);
		this.vbox15.Add(this.GtkScrolledWindow6);
		global::Gtk.Box.BoxChild w99 = ((global::Gtk.Box.BoxChild)(this.vbox15[this.GtkScrolledWindow6]));
		w99.Position = 1;
		this.vbox6.Add(this.vbox15);
		global::Gtk.Box.BoxChild w100 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.vbox15]));
		w100.Position = 1;
		this.notebook1.Add(this.vbox6);
		global::Gtk.Notebook.NotebookChild w101 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1[this.vbox6]));
		w101.Position = 5;
		// Notebook tab
		this.label6 = new global::Gtk.Label();
		this.label6.Name = "label6";
		this.label6.LabelProp = global::Mono.Unix.Catalog.GetString("page6");
		this.notebook1.SetTabLabel(this.vbox6, this.label6);
		this.label6.ShowAll();
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.vbox5 = new global::Gtk.VBox();
		this.vbox5.Name = "vbox5";
		this.vbox5.Spacing = 6;
		// Container child vbox5.Gtk.Box+BoxChild
		this.GtkScrolledWindow7 = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow7.Name = "GtkScrolledWindow7";
		this.GtkScrolledWindow7.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow7.Gtk.Container+ContainerChild
		this.nodeview8 = new global::Gtk.NodeView();
		this.nodeview8.CanFocus = true;
		this.nodeview8.Name = "nodeview8";
		this.GtkScrolledWindow7.Add(this.nodeview8);
		this.vbox5.Add(this.GtkScrolledWindow7);
		global::Gtk.Box.BoxChild w103 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.GtkScrolledWindow7]));
		w103.Position = 0;
		w103.Padding = ((uint)(20));
		// Container child vbox5.Gtk.Box+BoxChild
		this.hbox9 = new global::Gtk.HBox();
		this.hbox9.Name = "hbox9";
		this.hbox9.Spacing = 6;
		// Container child hbox9.Gtk.Box+BoxChild
		this.vbox27 = new global::Gtk.VBox();
		this.vbox27.Name = "vbox27";
		this.vbox27.Spacing = 6;
		// Container child vbox27.Gtk.Box+BoxChild
		this.hbox23 = new global::Gtk.HBox();
		this.hbox23.Name = "hbox23";
		this.hbox23.Spacing = 6;
		// Container child hbox23.Gtk.Box+BoxChild
		this.button3 = new global::Gtk.Button();
		this.button3.WidthRequest = 65;
		this.button3.CanFocus = true;
		this.button3.Name = "button3";
		this.button3.UseUnderline = true;
		this.button3.Label = global::Mono.Unix.Catalog.GetString("Clear");
		this.hbox23.Add(this.button3);
		global::Gtk.Box.BoxChild w104 = ((global::Gtk.Box.BoxChild)(this.hbox23[this.button3]));
		w104.Position = 1;
		w104.Fill = false;
		this.vbox27.Add(this.hbox23);
		global::Gtk.Box.BoxChild w105 = ((global::Gtk.Box.BoxChild)(this.vbox27[this.hbox23]));
		w105.Position = 0;
		w105.Expand = false;
		w105.Fill = false;
		this.hbox9.Add(this.vbox27);
		global::Gtk.Box.BoxChild w106 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.vbox27]));
		w106.Position = 0;
		this.vbox5.Add(this.hbox9);
		global::Gtk.Box.BoxChild w107 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.hbox9]));
		w107.Position = 1;
		this.notebook1.Add(this.vbox5);
		global::Gtk.Notebook.NotebookChild w108 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1[this.vbox5]));
		w108.Position = 6;
		// Notebook tab
		this.label8 = new global::Gtk.Label();
		this.label8.Name = "label8";
		this.label8.LabelProp = global::Mono.Unix.Catalog.GetString("page8");
		this.notebook1.SetTabLabel(this.vbox5, this.label8);
		this.label8.ShowAll();
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.vbox17 = new global::Gtk.VBox();
		this.vbox17.Name = "vbox17";
		this.vbox17.Spacing = 6;
		// Container child vbox17.Gtk.Box+BoxChild
		this.GtkScrolledWindow2 = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow2.Name = "GtkScrolledWindow2";
		this.GtkScrolledWindow2.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow2.Gtk.Container+ContainerChild
		this.nodeview3 = new global::Gtk.NodeView();
		this.nodeview3.CanFocus = true;
		this.nodeview3.Name = "nodeview3";
		this.GtkScrolledWindow2.Add(this.nodeview3);
		this.vbox17.Add(this.GtkScrolledWindow2);
		global::Gtk.Box.BoxChild w110 = ((global::Gtk.Box.BoxChild)(this.vbox17[this.GtkScrolledWindow2]));
		w110.Position = 0;
		// Container child vbox17.Gtk.Box+BoxChild
		this.vbox18 = new global::Gtk.VBox();
		this.vbox18.Name = "vbox18";
		this.vbox18.Spacing = 6;
		// Container child vbox18.Gtk.Box+BoxChild
		this.hbox20 = new global::Gtk.HBox();
		this.hbox20.Name = "hbox20";
		this.hbox20.Spacing = 6;
		// Container child hbox20.Gtk.Box+BoxChild
		this.label7 = new global::Gtk.Label();
		this.label7.Name = "label7";
		this.label7.Ypad = 10;
		this.label7.LabelProp = global::Mono.Unix.Catalog.GetString("Number of trainings by player:");
		this.hbox20.Add(this.label7);
		global::Gtk.Box.BoxChild w111 = ((global::Gtk.Box.BoxChild)(this.hbox20[this.label7]));
		w111.Position = 0;
		w111.Expand = false;
		w111.Fill = false;
		w111.Padding = ((uint)(40));
		// Container child hbox20.Gtk.Box+BoxChild
		this.label9 = new global::Gtk.Label();
		this.label9.Name = "label9";
		this.label9.LabelProp = global::Mono.Unix.Catalog.GetString("- -");
		this.hbox20.Add(this.label9);
		global::Gtk.Box.BoxChild w112 = ((global::Gtk.Box.BoxChild)(this.hbox20[this.label9]));
		w112.Position = 1;
		w112.Expand = false;
		w112.Fill = false;
		this.vbox18.Add(this.hbox20);
		global::Gtk.Box.BoxChild w113 = ((global::Gtk.Box.BoxChild)(this.vbox18[this.hbox20]));
		w113.Position = 0;
		w113.Expand = false;
		w113.Fill = false;
		// Container child vbox18.Gtk.Box+BoxChild
		this.hbox21 = new global::Gtk.HBox();
		this.hbox21.Name = "hbox21";
		this.hbox21.Spacing = 6;
		// Container child hbox21.Gtk.Box+BoxChild
		this.label18 = new global::Gtk.Label();
		this.label18.Name = "label18";
		this.label18.Ypad = 10;
		this.label18.LabelProp = global::Mono.Unix.Catalog.GetString("Number of trainings in total:");
		this.hbox21.Add(this.label18);
		global::Gtk.Box.BoxChild w114 = ((global::Gtk.Box.BoxChild)(this.hbox21[this.label18]));
		w114.Position = 0;
		w114.Expand = false;
		w114.Fill = false;
		w114.Padding = ((uint)(40));
		// Container child hbox21.Gtk.Box+BoxChild
		this.label23 = new global::Gtk.Label();
		this.label23.Name = "label23";
		this.label23.LabelProp = global::Mono.Unix.Catalog.GetString("- -");
		this.hbox21.Add(this.label23);
		global::Gtk.Box.BoxChild w115 = ((global::Gtk.Box.BoxChild)(this.hbox21[this.label23]));
		w115.Position = 1;
		w115.Expand = false;
		w115.Fill = false;
		w115.Padding = ((uint)(10));
		this.vbox18.Add(this.hbox21);
		global::Gtk.Box.BoxChild w116 = ((global::Gtk.Box.BoxChild)(this.vbox18[this.hbox21]));
		w116.Position = 1;
		w116.Expand = false;
		w116.Fill = false;
		// Container child vbox18.Gtk.Box+BoxChild
		this.hbox22 = new global::Gtk.HBox();
		this.hbox22.Name = "hbox22";
		this.hbox22.Spacing = 6;
		// Container child hbox22.Gtk.Box+BoxChild
		this.label24 = new global::Gtk.Label();
		this.label24.Name = "label24";
		this.label24.Ypad = 10;
		this.label24.LabelProp = global::Mono.Unix.Catalog.GetString("In percentage (%):");
		this.hbox22.Add(this.label24);
		global::Gtk.Box.BoxChild w117 = ((global::Gtk.Box.BoxChild)(this.hbox22[this.label24]));
		w117.Position = 0;
		w117.Expand = false;
		w117.Fill = false;
		w117.Padding = ((uint)(40));
		// Container child hbox22.Gtk.Box+BoxChild
		this.label27 = new global::Gtk.Label();
		this.label27.Name = "label27";
		this.label27.LabelProp = global::Mono.Unix.Catalog.GetString("- -");
		this.hbox22.Add(this.label27);
		global::Gtk.Box.BoxChild w118 = ((global::Gtk.Box.BoxChild)(this.hbox22[this.label27]));
		w118.Position = 1;
		w118.Expand = false;
		w118.Fill = false;
		w118.Padding = ((uint)(63));
		this.vbox18.Add(this.hbox22);
		global::Gtk.Box.BoxChild w119 = ((global::Gtk.Box.BoxChild)(this.vbox18[this.hbox22]));
		w119.Position = 2;
		w119.Expand = false;
		w119.Fill = false;
		this.vbox17.Add(this.vbox18);
		global::Gtk.Box.BoxChild w120 = ((global::Gtk.Box.BoxChild)(this.vbox17[this.vbox18]));
		w120.Position = 1;
		w120.Expand = false;
		w120.Fill = false;
		this.notebook1.Add(this.vbox17);
		global::Gtk.Notebook.NotebookChild w121 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1[this.vbox17]));
		w121.Position = 7;
		// Notebook tab
		this.label28 = new global::Gtk.Label();
		this.label28.Name = "label28";
		this.label28.LabelProp = global::Mono.Unix.Catalog.GetString("page9");
		this.notebook1.SetTabLabel(this.vbox17, this.label28);
		this.label28.ShowAll();
		this.vbox1.Add(this.notebook1);
		global::Gtk.Box.BoxChild w122 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.notebook1]));
		w122.Position = 1;
		this.Add(this.vbox1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 839;
		this.DefaultHeight = 498;
		this.Show();
		this.NewPlayerAction.Activated += new global::System.EventHandler(this.OnNewPlayer);
		this.EditPlayerAction.Activated += new global::System.EventHandler(this.OnEditPlayer);
		this.StartAction.Activated += new global::System.EventHandler(this.OnSeasonStart);
		this.EditAction.Activated += new global::System.EventHandler(this.OnSeasonEdit);
		this.StartAction1.Activated += new global::System.EventHandler(this.OnStartTraining);
		this.NewTypeAction.Activated += new global::System.EventHandler(this.OnAddNewType);
		this.ViewAction.Activated += new global::System.EventHandler(this.OnView);
		this.ExitAction.Activated += new global::System.EventHandler(this.OnExit);
		this.ViewRecordsAction.Activated += new global::System.EventHandler(this.OnViewRercords);
		this.button2.Clicked += new global::System.EventHandler(this.OnSavePlayer);
		this.button1.Clicked += new global::System.EventHandler(this.OnClickDelete);
		this.button5.Clicked += new global::System.EventHandler(this.OnButtonUpdate);
		this.button6.Clicked += new global::System.EventHandler(this.OnSaveSeasson);
		this.button7.Clicked += new global::System.EventHandler(this.OnUpdateSeasson);
		this.button4.Clicked += new global::System.EventHandler(this.SaveTraining);
		this.button3.Clicked += new global::System.EventHandler(this.OnClear);
	}
}
